export const MAGIC_GRADIENT = 'linear-gradient(135deg, #FFB300 0%, #FF6F00 45%, #8E24AA 100%)';

export const SOURCE_COPY = {
  ai: { label: 'AI insight', hint: 'Generated by our AI partner from the summary, genres and, optionally, viewer comments.' },
  fallback: {
    label: "Bee's instinct",
    hint: 'Our AI partner is resting right now, so Bee TV compiled this insight with its offline engine.',
  },
} as const;
